import { FormEvent, useState } from "react";
import { Link, Navigate, useNavigate } from "react-router-dom";
import { ButtonSpinner } from "../components/LoadingSpinner";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";

export function RegisterPage() {
  const { register, user } = useAuth(); const navigate = useNavigate(); const { showToast } = useToast();
  const [form, setForm] = useState({ full_name: "", email: "", phone: "", password: "" }); const [showPassword, setShowPassword] = useState(false); const [busy, setBusy] = useState(false);
  if (user) return <Navigate to="/dashboard" replace />;
  const submit = async (event: FormEvent) => { event.preventDefault(); if (busy) return; setBusy(true); try { await register({ ...form, phone: form.phone || undefined }); setBusy(false); await new Promise<void>((resolve) => requestAnimationFrame(() => resolve())); showToast("Registration successful. Welcome to PriceYard."); navigate("/dashboard", { replace: true }); } catch (err) { setBusy(false); await new Promise<void>((resolve) => requestAnimationFrame(() => resolve())); showToast(err instanceof Error ? err.message : "Registration failed.", "error"); } };
  return <section className="page auth-page"><div className="auth-card"><span className="eyebrow">14-day trial</span><h1>Create your PriceYard account</h1><p>New normal users begin with the approved 14-day trial flow.</p><form className="form-stack" onSubmit={submit}><label>Full name<input required value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })} /></label><label>Email<input type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Phone <small>(optional)</small><input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label>Password <small>(minimum 8 characters)</small><div className="password-field"><input id="register-password" type={showPassword ? "text" : "password"} required minLength={8} maxLength={72} autoComplete="new-password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><button type="button" className="password-toggle" onClick={() => setShowPassword((visible) => !visible)} aria-controls="register-password" aria-pressed={showPassword} aria-label={showPassword ? "Hide password" : "Show password"}>{showPassword ? "Hide" : "Show"}</button></div></label><button className="button" disabled={busy}>{busy ? <ButtonSpinner label="Please wait…" /> : "Register"}</button></form><p className="muted">Already registered? <Link className="text-link" to="/login">Log in</Link>.</p></div></section>;
}
