import { FormEvent, useEffect, useMemo, useState } from "react";
import { useAuth } from "../context/AuthContext";
import { apiFetch } from "../services/api";
import type { Commodity, Market, WatchlistItem } from "../types/api";

export function WatchlistPage() {
  const { token } = useAuth(); const [items, setItems] = useState<WatchlistItem[]>([]); const [commodities, setCommodities] = useState<Commodity[]>([]); const [markets, setMarkets] = useState<Market[]>([]); const [commodityId, setCommodityId] = useState(""); const [marketId, setMarketId] = useState(""); const [error, setError] = useState("");
  const load = async () => { if (!token) return; try { setItems(await apiFetch<WatchlistItem[]>("/watchlist", {}, token)); setError(""); } catch (err) { setError((err as Error).message); } };
  useEffect(() => { void load(); apiFetch<Commodity[]>("/commodities").then(setCommodities).catch(() => undefined); apiFetch<Market[]>("/markets").then(setMarkets).catch(() => undefined); }, [token]);
  const commodityMap = useMemo(() => new Map(commodities.map((x) => [x.id, x.name])), [commodities]); const marketMap = useMemo(() => new Map(markets.map((x) => [x.id, x.name])), [markets]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!token || (!commodityId && !marketId)) { setError("Choose a commodity, a market, or both."); return; } try { await apiFetch("/watchlist", { method: "POST", body: JSON.stringify({ commodity_id: commodityId ? Number(commodityId) : null, market_id: marketId ? Number(marketId) : null }) }, token); setCommodityId(""); setMarketId(""); await load(); } catch (err) { setError((err as Error).message); } };
  const remove = async (id: number) => { if (!token) return; try { await apiFetch(`/watchlist/${id}`, { method: "DELETE" }, token); await load(); } catch (err) { setError((err as Error).message); } };
  return <section className="page page-section"><div className="page-title"><span className="eyebrow">Your saved interests</span><h1>Watchlist</h1><p>Save a commodity, a market, or both. Target-price alerts remain deferred.</p></div><form className="filter-bar" onSubmit={submit}><label>Commodity<select value={commodityId} onChange={(e) => setCommodityId(e.target.value)}><option value="">No commodity</option>{commodities.filter((x) => x.is_active).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Market<select value={marketId} onChange={(e) => setMarketId(e.target.value)}><option value="">No market</option>{markets.filter((x) => x.is_active).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div className="filter-actions"><button className="button button-small">Save item</button></div></form>{error && <div className="status-box error">{error}</div>}<div className="watchlist-grid">{items.map((item) => <article className="card" key={item.id}><span className="eyebrow">Saved item</span><h3>{item.commodity_id ? commodityMap.get(item.commodity_id) || `Commodity #${item.commodity_id}` : "All commodities"}</h3><p>{item.market_id ? marketMap.get(item.market_id) || `Market #${item.market_id}` : "No market restriction"}</p><button className="button button-danger button-small" onClick={() => void remove(item.id)}>Remove</button></article>)}</div>{!items.length && !error && <div className="status-box">Your watchlist is empty.</div>}</section>;
}
