import { FormEvent, useState } from "react";
import { apiFetch } from "../../services/api";
import type { MarketSignal, QualitySignal } from "../../types/api";
import { AdminActionButton, AdminLoading, AdminStatus, errorText, optionalNumber, useAdminList } from "./adminUtils";

const actions = ["", "Watch", "Investigate", "Buy Carefully", "Hold", "Sell Carefully"];
export function AdminMarketSignalsPage() {
  const { data, loading, error: loadError, reload, token } = useAdminList<MarketSignal>("/market-signals"); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault(); if(!token||busy)return; const f=new FormData(e.currentTarget); const id=String(f.get("id")||"").trim(); const payload={commodity_id:Number(f.get("commodity_id")),market_id:Number(f.get("market_id")),price_update_id:optionalNumber(f.get("price_update_id")),signal_type:String(f.get("signal_type")),signal_description:String(f.get("signal_description")),possible_meaning:String(f.get("possible_meaning")||"")||null,suggested_action:String(f.get("suggested_action")||"")||null}; setBusy(true);try{await apiFetch(id?`/market-signals/${id}`:"/market-signals",{method:id?"PATCH":"POST",body:JSON.stringify(payload)},token);setMessage(id?"Market signal updated.":"Market signal created.");setError("");await reload();}catch(err){setError(errorText(err));}finally{setBusy(false);}}
  async function remove(id:number){if(!token||busy||!confirm("Delete this market signal?"))return;setBusy(true);try{await apiFetch(`/market-signals/${id}`,{method:"DELETE"},token);setMessage("Market signal deleted.");await reload();}catch(err){setError(errorText(err));}finally{setBusy(false);}}
  return <div><h2>Market signals</h2><AdminStatus error={error||loadError} success={message}/><form className="form-stack card admin-form" onSubmit={submit}><div className="form-grid"><label>ID to edit (blank=create)<input name="id" type="number" min="1"/></label><label>Commodity ID<input name="commodity_id" type="number" min="1" required/></label><label>Market ID<input name="market_id" type="number" min="1" required/></label><label>Price update ID<input name="price_update_id" type="number" min="1"/></label><label>Signal type<input name="signal_type" required/></label><label>Suggested Action<select name="suggested_action">{actions.map(x=><option value={x} key={x}>{x||"None"}</option>)}</select></label></div><label>Description<textarea name="signal_description" required/></label><label>Possible Meaning<textarea name="possible_meaning"/></label><AdminActionButton className="button" type="submit" busy={busy}>Save market signal</AdminActionButton></form>{loading?<AdminLoading label="Loading market signals…"/>:<div className="admin-card-list">{data.map(x=><article className="card" key={x.id}><div className="card-row"><div><span className="eyebrow">#{x.id} · {x.signal_type}</span><h3>{x.signal_description}</h3><p>{x.possible_meaning||"No meaning note"}</p><small>{x.suggested_action||"No action"}</small></div><AdminActionButton className="button button-small button-danger" busy={busy} onClick={()=>void remove(x.id)}>Delete</AdminActionButton></div></article>)}</div>}</div>;
}

export function AdminQualitySignalsPage() {
  const { data, loading, error: loadError, reload, token } = useAdminList<QualitySignal>("/quality-signals"); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token||busy)return;const f=new FormData(e.currentTarget);const id=String(f.get("id")||"").trim();const payload={commodity_id:Number(f.get("commodity_id")),market_id:Number(f.get("market_id")),price_update_id:optionalNumber(f.get("price_update_id")),quality_status:String(f.get("quality_status")||"")||null,moisture_status:String(f.get("moisture_status")||"")||null,storage_readiness:String(f.get("storage_readiness")||"")||null,risk_note:String(f.get("risk_note")||"")||null};setBusy(true);try{await apiFetch(id?`/quality-signals/${id}`:"/quality-signals",{method:id?"PATCH":"POST",body:JSON.stringify(payload)},token);setMessage(id?"Quality signal updated.":"Quality signal created.");setError("");await reload();}catch(err){setError(errorText(err));}finally{setBusy(false);}}
  async function remove(id:number){if(!token||busy||!confirm("Delete this quality signal?"))return;setBusy(true);try{await apiFetch(`/quality-signals/${id}`,{method:"DELETE"},token);setMessage("Quality signal deleted.");await reload();}catch(err){setError(errorText(err));}finally{setBusy(false);}}
  return <div><h2>Quality signals</h2><AdminStatus error={error||loadError} success={message}/><form className="form-stack card admin-form" onSubmit={submit}><div className="form-grid"><label>ID to edit (blank=create)<input name="id" type="number" min="1"/></label><label>Commodity ID<input name="commodity_id" type="number" min="1" required/></label><label>Market ID<input name="market_id" type="number" min="1" required/></label><label>Price update ID<input name="price_update_id" type="number" min="1"/></label><label>Quality status<input name="quality_status"/></label><label>Moisture status<input name="moisture_status"/></label><label>Storage readiness<input name="storage_readiness"/></label></div><label>Risk note<textarea name="risk_note"/></label><AdminActionButton className="button" type="submit" busy={busy}>Save quality signal</AdminActionButton></form>{loading?<AdminLoading label="Loading quality signals…"/>:<div className="admin-card-list">{data.map(x=><article className="card" key={x.id}><div className="card-row"><div><span className="eyebrow">Signal #{x.id}</span><h3>{x.quality_status||"Quality observation"}</h3><p>{x.risk_note||"No risk note"}</p><small>Moisture: {x.moisture_status||"—"} · Storage: {x.storage_readiness||"—"}</small></div><AdminActionButton className="button button-small button-danger" busy={busy} onClick={()=>void remove(x.id)}>Delete</AdminActionButton></div></article>)}</div>}</div>;
}
