import { FormEvent, useState } from "react";
import { CommodityImage } from "../../components/CommodityImage";
import { apiFetch } from "../../services/api";
import type { Commodity } from "../../types/api";
import { AdminActionButton, AdminLoading, AdminStatus, errorText, useAdminList } from "./adminUtils";

export function AdminCommoditiesPage() {
  const { data, loading, error: loadError, reload, token } = useAdminList<Commodity>("/commodities/admin/all");
  const [editing, setEditing] = useState<Commodity | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!token || busy) return; const form = e.currentTarget; const f = new FormData(form); const payload = { name: String(f.get("name")), description: String(f.get("description") || "") || null, image_url: String(f.get("image_url") || "").trim() || null, is_active: f.get("is_active") === "on", is_upcoming: f.get("is_upcoming") === "on", expected_available_date: String(f.get("expected_available_date") || "").trim() || null }; setBusy(true); try { if (editing) await apiFetch(`/commodities/${editing.id}`, { method: "PATCH", body: JSON.stringify(payload) }, token); else await apiFetch("/commodities", { method: "POST", body: JSON.stringify(payload) }, token); setEditing(null); form.reset(); setMessage(editing ? "Commodity updated." : "Commodity created."); setError(""); await reload(); } catch (err) { setError(errorText(err)); setMessage(""); } finally { setBusy(false); } }
  async function remove(id: number) { if (!token || busy || !confirm("Delete this commodity?")) return; setBusy(true); try { await apiFetch(`/commodities/${id}`, { method: "DELETE" }, token); setMessage("Commodity deleted."); await reload(); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } }
  return <div><h2>Commodities</h2><AdminStatus error={error || loadError} success={message} /><form key={editing?.id ?? "new"} className="form-stack card admin-form" onSubmit={submit}><label>Name<input name="name" defaultValue={editing?.name || ""} required /></label><label>Description<textarea name="description" defaultValue={editing?.description || ""} /></label><label>Image URL (optional)<input name="image_url" type="url" placeholder="https://example.com/egusi.jpg" defaultValue={editing?.image_url || ""} /></label><label className="check-row"><input type="checkbox" name="is_active" defaultChecked={editing?.is_active ?? true} /> Active</label><label className="check-row"><input type="checkbox" name="is_upcoming" defaultChecked={editing?.is_upcoming ?? false} /> Upcoming (show in "Coming Soon")</label><label>Expected available date (optional)<input name="expected_available_date" type="date" defaultValue={editing?.expected_available_date || ""} /></label><div className="button-row"><AdminActionButton className="button" type="submit" busy={busy}>{editing ? "Save commodity" : "Create commodity"}</AdminActionButton>{editing && <button className="button button-secondary" type="button" disabled={busy} onClick={() => setEditing(null)}>Cancel</button>}</div></form>
    {loading ? <AdminLoading label="Loading commodities…" /> : <div className="admin-card-list">{data.map((item) => <article className="card" key={item.id}><div className="card-row"><div className="admin-commodity-info"><CommodityImage src={item.image_url} alt={item.name} className="commodity-image-small" /><div><h3>{item.name}</h3><p>{item.description || "No description"}</p><small>{item.is_active ? "Active" : "Inactive"}{item.is_upcoming ? " · Upcoming" : ""}</small></div></div><div className="button-row"><button className="button button-small button-secondary" disabled={busy} onClick={() => setEditing(item)}>Edit</button><AdminActionButton className="button button-small button-danger" busy={busy} onClick={() => void remove(item.id)}>Delete</AdminActionButton></div></div></article>)}</div>}
  </div>;
}
