import { FormEvent, useEffect, useState } from "react";
import { apiFetch } from "../../services/api";
import { useAuth } from "../../context/AuthContext";
import type { Commodity, Market, PriceUpdate } from "../../types/api";
import { AdminStatus, errorText, useAdminList } from "./adminUtils";

const actions = ["Watch", "Investigate", "Buy Carefully", "Hold", "Sell Carefully"];
export function AdminPriceUpdatesPage() {
  const { token } = useAuth();
  const { data: history, loading, error: loadError, reload } = useAdminList<PriceUpdate>("/price-updates/history");
  const [commodities, setCommodities] = useState<Commodity[]>([]); const [markets, setMarkets] = useState<Market[]>([]);
  const [created, setCreated] = useState<PriceUpdate[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [targetId, setTargetId] = useState("");
  useEffect(() => { if (!token) return; void Promise.all([apiFetch<Commodity[]>("/commodities", {}, token), apiFetch<Market[]>("/markets", {}, token)]).then(([c,m]) => { setCommodities(c); setMarkets(m); }).catch((err) => setError(errorText(err))); }, [token]);
  async function create(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!token) return; const f = new FormData(e.currentTarget); const payload = {
    commodity_id: Number(f.get("commodity_id")), market_id: Number(f.get("market_id")), price_low: Number(f.get("price_low")), price_high: Number(f.get("price_high")), average_price: Number(f.get("average_price")), previous_price_low: String(f.get("previous_price_low") || "") ? Number(f.get("previous_price_low")) : null, previous_price_high: String(f.get("previous_price_high") || "") ? Number(f.get("previous_price_high")) : null,
    unit: String(f.get("unit")), bag_size: String(f.get("bag_size") || "") || null, commodity_type: String(f.get("commodity_type") || "") || null, market_day: String(f.get("market_day") || "") || null, time_of_day: String(f.get("time_of_day") || "") || null, movement: String(f.get("movement")), confidence_level: String(f.get("confidence_level")), source_type: String(f.get("source_type") || "") || null, source_1: String(f.get("source_1") || "") || null, source_2: String(f.get("source_2") || "") || null, update_date_time: String(f.get("update_date_time")), is_outdated: false, possible_meaning: String(f.get("possible_meaning")), suggested_action: String(f.get("suggested_action")), notes: String(f.get("notes") || "") || null,
  }; try { const item = await apiFetch<PriceUpdate>("/price-updates", { method: "POST", body: JSON.stringify(payload) }, token); setCreated((items) => [item, ...items]); setTargetId(String(item.id)); setMessage(`Price update #${item.id} created pending approval.`); setError(""); } catch (err) { setError(errorText(err)); setMessage(""); } }
  async function act(action: "approve"|"reject"|"mark-outdated"|"delete") { if (!token || !targetId) return; try { if (action === "delete") await apiFetch(`/price-updates/${targetId}`, { method: "DELETE" }, token); else await apiFetch(`/price-updates/${targetId}/${action}`, { method: "PATCH" }, token); setMessage(`Price update #${targetId}: ${action} completed.`); setError(""); await reload(); } catch (err) { setError(errorText(err)); } }
  async function editGuidance(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!token || !targetId) return; const f = new FormData(e.currentTarget); try { await apiFetch(`/price-updates/${targetId}`, { method: "PATCH", body: JSON.stringify({ possible_meaning: String(f.get("possible_meaning")), suggested_action: String(f.get("suggested_action")) }) }, token); setMessage(`Possible Meaning / Suggested Action updated on #${targetId}.`); setError(""); await reload(); } catch (err) { setError(errorText(err)); } }
  const rows = [...created, ...history.filter((h) => !created.some((c) => c.id === h.id))];
  return <div><h2>Price updates</h2><p className="muted">Create records, edit guidance, approve/reject, mark outdated, or delete by record ID. Public history below shows approved records; newly created pending records remain visible in this session.</p><AdminStatus error={error || loadError} success={message} />
    <form className="form-stack card admin-form" onSubmit={create}><div className="form-grid"><label>Commodity<select name="commodity_id" required>{commodities.map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Market<select name="market_id" required>{markets.map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Low<input name="price_low" type="number" min="0" step="0.01" required /></label><label>High<input name="price_high" type="number" min="0" step="0.01" required /></label><label>Average<input name="average_price" type="number" min="0" step="0.01" required /></label><label>Unit<input name="unit" defaultValue="bag" required /></label><label>Previous low<input name="previous_price_low" type="number" min="0" step="0.01" /></label><label>Previous high<input name="previous_price_high" type="number" min="0" step="0.01" /></label><label>Bag size<input name="bag_size" /></label><label>Commodity type<input name="commodity_type" /></label><label>Market day<select name="market_day"><option value="">Unknown</option>{["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].map((d) => <option key={d}>{d}</option>)}</select></label><label>Time of day<select name="time_of_day"><option value="">Unknown</option>{["morning","afternoon","evening","closing"].map((d) => <option key={d}>{d}</option>)}</select></label><label>Movement<select name="movement" defaultValue="unknown">{["up","down","stable","unknown"].map((x) => <option key={x}>{x}</option>)}</select></label><label>Confidence<select name="confidence_level" defaultValue="Reporter submitted">{["Reporter submitted", "Verified by 2 sources", "Admin confirmed", "Market visit confirmed", "Low confidence", "Price outdated"].map((x) => <option key={x}>{x}</option>)}</select></label><label>Source type<input name="source_type" /></label><label>Update date/time<input name="update_date_time" type="datetime-local" required /></label><label>Source 1 (private)<input name="source_1" /></label><label>Source 2 (private)<input name="source_2" /></label></div><label>Possible Meaning<textarea name="possible_meaning" required /></label><label>Suggested Action<select name="suggested_action">{actions.map((x) => <option key={x}>{x}</option>)}</select></label><label>Notes<textarea name="notes" /></label><button className="button" type="submit">Create pending update</button></form>
    <div className="admin-action-panel"><label>Record ID<input value={targetId} onChange={(e) => setTargetId(e.target.value)} inputMode="numeric" /></label><div className="button-row"><button className="button button-small" onClick={() => void act("approve")}>Approve</button><button className="button button-small button-secondary" onClick={() => void act("reject")}>Reject</button><button className="button button-small button-secondary" onClick={() => void act("mark-outdated")}>Mark outdated</button><button className="button button-small button-danger" onClick={() => void act("delete")}>Delete</button></div></div>
    <form className="form-stack card admin-form" onSubmit={editGuidance}><h3>Edit Possible Meaning / Suggested Action</h3><p className="muted">Uses the record ID above.</p><label>Possible Meaning<textarea name="possible_meaning" required /></label><label>Suggested Action<select name="suggested_action">{actions.map((x) => <option key={x}>{x}</option>)}</select></label><button className="button" type="submit">Save guidance</button></form>
    {loading ? <div className="status-box">Loading price history…</div> : <div className="table-wrap"><table className="admin-table"><thead><tr><th>ID</th><th>Commodity / market</th><th>Range</th><th>Status</th><th>Meaning / action</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id} onClick={() => setTargetId(String(item.id))}><td>{item.id}</td><td>{item.commodity?.name || item.commodity_id}<small>{item.market?.name || item.market_id}</small></td><td>{item.price_low} – {item.price_high}</td><td>{item.status}{item.is_outdated ? " · outdated" : ""}</td><td>{item.possible_meaning}<small>{item.suggested_action}</small></td></tr>)}</tbody></table></div>}
  </div>;
}
