import { FormEvent, useState } from "react";
import { apiFetch } from "../../services/api";
import type { Market } from "../../types/api";
import { AdminActionButton, AdminLoading, AdminStatus, errorText, useAdminList } from "./adminUtils";

export function AdminMarketsPage() {
  const { data, loading, error: loadError, reload, token } = useAdminList<Market>("/markets");
  const [editing, setEditing] = useState<Market | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!token || busy) return; const form = e.currentTarget; const f = new FormData(form); const day = String(f.get("market_day") || ""); const payload = { name: String(f.get("name")), state: String(f.get("state") || "") || null, country: String(f.get("country") || "Nigeria"), market_day: day || null, description: String(f.get("description") || "") || null, is_active: f.get("is_active") === "on" }; setBusy(true); try { if (editing) await apiFetch(`/markets/${editing.id}`, { method: "PATCH", body: JSON.stringify(payload) }, token); else await apiFetch("/markets", { method: "POST", body: JSON.stringify(payload) }, token); setEditing(null); form.reset(); setMessage(editing ? "Market updated." : "Market created."); setError(""); await reload(); } catch (err) { setError(errorText(err)); setMessage(""); } finally { setBusy(false); } }
  async function remove(id: number) { if (!token || busy || !confirm("Delete this market?")) return; setBusy(true); try { await apiFetch(`/markets/${id}`, { method: "DELETE" }, token); setMessage("Market deleted."); await reload(); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } }
  return <div><h2>Markets</h2><AdminStatus error={error || loadError} success={message} /><form key={editing?.id ?? "new"} className="form-stack card admin-form" onSubmit={submit}><div className="form-grid"><label>Name<input name="name" defaultValue={editing?.name || ""} required /></label><label>State<input name="state" defaultValue={editing?.state || ""} /></label><label>Country<input name="country" defaultValue={editing?.country || "Nigeria"} required /></label><label>Market day<select name="market_day" defaultValue={editing?.market_day || ""}><option value="">Not verified</option>{["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].map((day) => <option key={day}>{day}</option>)}</select></label></div><label>Description<textarea name="description" defaultValue={editing?.description || ""} /></label><label className="check-row"><input type="checkbox" name="is_active" defaultChecked={editing?.is_active ?? true} /> Active</label><div className="button-row"><AdminActionButton className="button" type="submit" busy={busy}>{editing ? "Save market" : "Create market"}</AdminActionButton>{editing && <button className="button button-secondary" type="button" disabled={busy} onClick={() => setEditing(null)}>Cancel</button>}</div></form>
    {loading ? <AdminLoading label="Loading markets…" /> : <div className="admin-card-list">{data.map((item) => <article className="card" key={item.id}><div className="card-row"><div><h3>{item.name}</h3><p>{item.state || "—"} · {item.market_day || "Market day not verified"}</p><small>{item.is_active ? "Active" : "Inactive"}</small></div><div className="button-row"><button className="button button-small button-secondary" disabled={busy} onClick={() => setEditing(item)}>Edit</button><AdminActionButton className="button button-small button-danger" busy={busy} onClick={() => void remove(item.id)}>Delete</AdminActionButton></div></div></article>)}</div>}
  </div>;
}
