import { FormEvent, useState } from "react";
import { apiFetch } from "../../services/api";
import type { FAQItem } from "../../types/api";
import { AdminStatus, errorText, useAdminList } from "./adminUtils";

type FAQAdmin = FAQItem & { is_published: boolean; created_by: number };
export function AdminFAQPage(){
 const {data:published,loading,error:loadError,reload,token}=useAdminList<FAQItem>("/faq"); const [sessionItems,setSessionItems]=useState<FAQAdmin[]>([]); const [targetId,setTargetId]=useState(""); const [error,setError]=useState("");const [message,setMessage]=useState("");
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;const f=new FormData(e.currentTarget);try{const item=await apiFetch<FAQAdmin>("/faq",{method:"POST",body:JSON.stringify({question:String(f.get("question")),answer:String(f.get("answer")),category:String(f.get("category"))})},token);setSessionItems(items=>[item,...items]);setTargetId(String(item.id));setMessage(`FAQ #${item.id} created hidden.`);setError("");}catch(err){setError(errorText(err));}}
 async function edit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token||!targetId)return;const f=new FormData(e.currentTarget);try{const item=await apiFetch<FAQAdmin>(`/faq/${targetId}`,{method:"PATCH",body:JSON.stringify({question:String(f.get("question")),answer:String(f.get("answer")),category:String(f.get("category"))})},token);setSessionItems(items=>[item,...items.filter(x=>x.id!==item.id)]);setMessage(`FAQ #${targetId} updated.`);setError("");await reload();}catch(err){setError(errorText(err));}}
 async function action(kind:"publish"|"hide"|"delete"){if(!token||!targetId)return;try{if(kind==="delete")await apiFetch(`/faq/${targetId}`,{method:"DELETE"},token);else{const item=await apiFetch<FAQAdmin>(`/faq/${targetId}/${kind}`,{method:"PATCH"},token);setSessionItems(items=>[item,...items.filter(x=>x.id!==item.id)]);}setMessage(`FAQ #${targetId}: ${kind} completed.`);setError("");await reload();}catch(err){setError(errorText(err));}}
 return <div><h2>FAQ</h2><p className="muted">New FAQs start hidden. Hidden items created during this session remain listed below; any known FAQ ID can be edited/published/hidden/deleted.</p><AdminStatus error={error||loadError} success={message}/><form className="form-stack card admin-form" onSubmit={create}><label>Question<input name="question" required/></label><label>Answer<textarea name="answer" required/></label><label>Category<input name="category" required/></label><button className="button">Create hidden FAQ</button></form><div className="admin-action-panel"><label>FAQ ID<input value={targetId} onChange={e=>setTargetId(e.target.value)} type="number" min="1"/></label><div className="button-row"><button className="button button-small" onClick={()=>void action("publish")}>Publish</button><button className="button button-small button-secondary" onClick={()=>void action("hide")}>Hide</button><button className="button button-small button-danger" onClick={()=>void action("delete")}>Delete</button></div></div><form className="form-stack card admin-form" onSubmit={edit}><h3>Edit known FAQ ID</h3><label>Question<input name="question" required/></label><label>Answer<textarea name="answer" required/></label><label>Category<input name="category" required/></label><button className="button">Save FAQ</button></form>
 <h3>Published FAQs</h3>{loading?<div className="status-box">Loading…</div>:<div className="admin-card-list">{published.map(x=><article className="card" key={x.id} onClick={()=>setTargetId(String(x.id))}><span className="eyebrow">#{x.id} · {x.category}</span><h3>{x.question}</h3><p>{x.answer}</p></article>)}</div>}
 {sessionItems.length>0&&<><h3>Session-managed FAQs</h3><div className="admin-card-list">{sessionItems.map(x=><article className="card" key={x.id} onClick={()=>setTargetId(String(x.id))}><span className="eyebrow">#{x.id} · {x.is_published?"Published":"Hidden"}</span><h3>{x.question}</h3><p>{x.answer}</p></article>)}</div></>}
 </div>;
}
